### ISSUE TITLE
Does RRC update CID?

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls-rrc#20]
We plug straight into [Section 6.5 of CID](https://www.rfc-editor.org/rfc/rfc9146.html#section-6-5).  So should this document update RFC9146?

**Comment by hannestschofenig** [comment]
I am not sure whether this is really an update. We do not change anything in RFC 9146, which is typically what the update means

**Comment by thomas-fossati** [comment]
SGMT; feel free to close this.
