### ISSUE TITLE
s/on-path/mitm/

### ISSUE THREAD

**Issue by thomas-fossati** [tlswg/dtls-rrc#31]
At the top of the "Attacker model" section we say: _"RRC is not designed to counter on-path attackers."_

What we should say instead is _"RRC is not designed to counter man-in-the-middle attackers."_

We do take care of on-path attackers, via the challenge/response exchange, and we should say that.

**Comment by ekr** [comment]
I don't think the CR exchange solves the problem, because the attacker can just change the IP addresses.
