### ISSUE TITLE
Is the select ... obsolete?

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-rrc#41]
```
struct {
    rrc_msg_type msg_type;
    select (return_routability_check.msg_type) {
        case path_challenge: Cookie;
        case path_response:  Cookie;
        case path_drop:      Cookie;
    };
} return_routability_check;
```

What are the considerations about that select? For me it looks like all "cases" are the same? Do I oversee something?

```
struct {
    rrc_msg_type msg_type;
    Cookie cookie;
} return_routability_check;
```

**Comment by boaks** [comment]
> Future extensions or additions to the Return Routability Check protocol may define new message types. Implementations MUST be able to parse and ignore unknown values.

Maybe the idea of that select is a "future extension". If so, "ignore unknown values" includes, to skip what ever follows, or?

Then maybe

> Implementations MUST be able to parse and ignore unknown values and the rest of the `return_routability_check`message.

**Comment by thomas-fossati** [comment]
Yep, exactly: RRC is not closed (see https://tlswg.org/dtls-rrc/draft-ietf-tls-dtls-rrc.html#section-10.3) so the select anticipates extensions that might need a value different from Cookie.

**Comment by boaks** [comment]
Thanks. WDYT about the extended formulation:

> Implementations MUST be able to parse and ignore unknown values together with the rest of the return_routability_check message.

**Comment by thomas-fossati** [comment]
I think the current text is already saying what you propose :-)

In the context of the paragraph, there is no "rest of the RRC message" that isn't the "unknown value", so the addition seems redundant to me.

@hannestschofenig WDYT?

**Comment by boaks** [comment]
Assuming:

```
struct {
    rrc_msg_type msg_type;
    select (return_routability_check.msg_type) {
        case path_challenge: Cookie;
        case path_response:  Cookie;
        case path_drop:      Cookie;
        case path_reset:      uint_8 tag;
    };
} return_routability_check;
```

If `path_reset` is unknown, what is then to be ignored?

Maybe:

> Implementations MUST be able to parse and ignore messages with an unknown `msg_type`.

**Comment by thomas-fossati** [comment]
> Implementations MUST be able to parse and ignore messages with an unknown msg_type

This is exactly what I wanted the current text to say.  Apparently I failed :-)

I'll do the suggested tweak.
