### ISSUE TITLE
on-path attacker 

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-rrc#44]
> An on-path attacker could make a copy of a packet, replace the source address with a spoofed one and forward it to the original destination. If the spoofed packet arrives before the original it will be regarded as a migration, while the original packet will be flagged as a duplicate and dropped.

For me this looks more like the off-path case.
On-path attacker may just replace the original package and only forward the spoofed one.

> An on-path attacker could replace the source address with a spoofed one and forward it to the destination. Assuming an "amplified response packet" this may be misused for a (D)Dos attack.

**Comment by thomas-fossati** [comment]
See also my comment on #48.  We need to rework this section starting from establishing shared terminology.
