### ISSUE TITLE
What does "counter" mean?

### ISSUE THREAD

**Issue by boaks** [tlswg/dtls-rrc#48]
> It is not possible for RRC to counter a man-in-the-middle attacker that is indistinguishable from a genuine network device. Such an attacker could, for example, drop, reorder or delay records at will. Man-in-the-middle attackers cannot craft DTLS records that would successfully pass verification due to the cryptographic protections applied by the DTLS record layer.

For me, "man-in-the-middle" is a synonym for "on-path".
If that text addresses the general "on-path" attacks in order to clarify, that RRC is no mitigation for these general "on-path-attacks", I think we should try to find an other text.

As idea, we may also refer to ideas to mitigate them, but explicitly exclude that from this draft.
e.g.:
- "reorder": don't use the record sequence number window, just drop all packets with no higher number (that drops then reordered packets).
- "delay records": maybe the first idea for an extension: execute a fresh RRC exchange and the next ip-packet must have a record sequence number higher as the one of the RRC message.

**Comment by boaks** [comment]
> An on-path attacker can:
> 
>    *  Inspect packets

> An on-path attacker cannot:
> 
>    *  Modify an authenticated portion of a packet and cause the
>       recipient to accept that packet

I miss, that 

> An on-path attacker cannot:
> 
>    *  Inspect the encrypted portion of a packet

I'm not sure, if we should "repeat" that. Do you know, if it's possible to just refer to that?

**Comment by thomas-fossati** [comment]
> I'm not sure, if we should "repeat" that. Do you know, if it's possible to just refer to that?

If it works for us as-is we can just reference the relevant sections.  We need to check that everything applies -- in particular whether we want to make the distinction between "on-path" and "limited on-path".
