### ISSUE TITLE
Potential ambiguity in value of timer

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls-rrc#57]
> In settings where there is external information about the RTT of the active path, implementations SHOULD use T = 3xRTT.
>
> If an implementation has no way to obtain information regarding the RTT of the active path, a value of 1s SHOULD be used.

In this second paragraph, does this mean T=1s or RTT=1s ?

**Comment by boaks** [comment]
FMPOV: 

`T=1s`

(because that refers to the default timeout of DTLS 1.2 RFC6347)
