### ISSUE TITLE
Figure 8 doesn't show probe on the previous path

### ISSUE THREAD

**Issue by martinthomson** [tlswg/dtls-rrc#58]
This is important and so the example should show it.

**Comment by boaks** [comment]
The RFC split the probes in [Basic](https://tlswg.org/dtls-rrc/draft-ietf-tls-dtls-rrc.html#section-7.1) and [Enhanced](https://tlswg.org/dtls-rrc/draft-ietf-tls-dtls-rrc.html#section-7.2).

The example demonstrates the `Basic` so I think, we should add that to the figure description "Basic Return Routability Example".
